---
- hosts: apache
  sudo: yes
  tasks:
    - name: install httpd
      yum: name=httpd state=installed

    - name: start httpd
      service: name=httpd state=started enabled=yes

    - name: stop iptables
      service: name=iptables state=stopped enabled=no

    - name: Transfer the script
       copy: src=hosts.sh dest=/opt/ mode=0777

    - name: execute the script
      command: sh /opt/hosts.sh

    - name: creating html pages
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: apache
        group: apache
        mode: 0644
      with_items:
        - {src: 'one.html.j2',dest: '/var/www/html/one/one.html'}
        - {src: 'two.html.j2',dest: '/var/www/html/two/two.html'}
        - {src: 'three.html.j2',dest: '/var/www/html/three/three.html'}

    - name: replace httpd.conf file
      command: cp -vf httpd.conf /etc/httpd/conf/httpd.conf
    handlers:
      - name: restart httpd
        service: name=httpd state=restarted